spring.application.name=email-microservice
spring.config.import=optional:file:.env[.properties],optional:file:email-microservice/.env[.properties]

server.port=${SERVER_PORT:8083}

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/email-service}

# RabbitMQ
spring.rabbitmq.addresses=${RABBITMQ_ADDRESSES}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.ssl.enabled=${RABBITMQ_SSL}

# SMTP (Gmail)
spring.mail.host=${EMAIL_HOST:smtp.gmail.com}
spring.mail.port=${EMAIL_PORT:587}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
