version: '3.9'

services:
  mysql:
    image: mysql:8.1
    container_name: mysql-container
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis-container
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  mysql-data: