version: '3.8'

services:
  mongo:
    container_name: EmailService-mongo
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: